export var AgriData = [
    {
        "timestamp": "1586507702",
        "state": "Andhra Pradesh",
        "district": "Chittor",
        "market": "Mulakalacheruvu",
        "commodity": "Tomato",
        "variety": "Local",
        "arrival_date": "10/04/2020",
        "min_price": "400",
        "max_price": "600",
        "modal_price": "500"
      },
      {
        "timestamp": "1586507702",
        "state": "Andhra Pradesh",
        "district": "Kurnool",
        "market": "Pattikonda",
        "commodity": "Tomato",
        "variety": "Local",
        "arrival_date": "10/04/2020",
        "min_price": "1000",
        "max_price": "1500",
        "modal_price": "1200"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Balrampur",
        "market": "Ramanujganj",
        "commodity": "Maize",
        "variety": "Local",
        "arrival_date": "10/04/2020",
        "min_price": "1770",
        "max_price": "1770",
        "modal_price": "1770"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Bilaspur",
        "market": "Tiphra",
        "commodity": "Onion",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "2300",
        "max_price": "2400",
        "modal_price": "2300"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Bilaspur",
        "market": "Tiphra",
        "commodity": "Potato",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "2300",
        "max_price": "2500",
        "modal_price": "2400"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Bilaspur",
        "market": "Tiphra",
        "commodity": "Tomato",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "500",
        "max_price": "600",
        "modal_price": "550"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Apple",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "10000",
        "max_price": "14000",
        "modal_price": "12000"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Banana - Green",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "800",
        "max_price": "1200",
        "modal_price": "1000"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Bhindi(Ladies Finger)",
        "variety": "Bhindi",
        "arrival_date": "10/04/2020",
        "min_price": "800",
        "max_price": "1200",
        "modal_price": "1000"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Bitter gourd",
        "variety": "Bitter Gourd",
        "arrival_date": "10/04/2020",
        "min_price": "1600",
        "max_price": "2000",
        "modal_price": "1800"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Bottle gourd",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "200",
        "max_price": "400",
        "modal_price": "300"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Brinjal",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "300",
        "max_price": "500",
        "modal_price": "400"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Cabbage",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "300",
        "max_price": "500",
        "modal_price": "400"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Capsicum",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "1200",
        "max_price": "1400",
        "modal_price": "1300"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Carrot",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "1000",
        "max_price": "1500",
        "modal_price": "1250"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Cauliflower",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "1600",
        "max_price": "2000",
        "modal_price": "1800"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Cucumbar(Kheera)",
        "variety": "Cucumbar",
        "arrival_date": "10/04/2020",
        "min_price": "800",
        "max_price": "1200",
        "modal_price": "1000"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Green Chilli",
        "variety": "Other",
        "arrival_date": "10/04/2020",
        "min_price": "1900",
        "max_price": "2000",
        "modal_price": "1950"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Guar",
        "variety": "Gwar",
        "arrival_date": "10/04/2020",
        "min_price": "2000",
        "max_price": "2400",
        "modal_price": "2200"
      },
      {
        "timestamp": "1586507702",
        "state": "Chattisgarh",
        "district": "Durg",
        "market": "Durg",
        "commodity": "Karbuja(Musk Melon)",
        "variety": "Karbhuja",
        "arrival_date": "10/04/2020",
        "min_price": "2000",
        "max_price": "2500",
        "modal_price": "2250"
      }
]